version: '3'

services:
  database.postgis:
    image: mdillon/postgis:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./services/database/postgis/.env
    volumes:
      - ./volumes/postgis:/var/lib/postgresql/data
